[build]
  command = "npm run build" # Build command for Vue project
  publish = "dist" # Folder where Vue project build files are output

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200